### ISSUE TITLE
Spam

### ISSUE THREAD

**Issue by vbonhomme** [ShakePeers/MediaKiki#28]
encore un peu de spammers qui s'inscrivent, sans trop foutre le bordel après. on peut les fusionner à la main mais bon, pteut être qu'à moyer terme il nous faudrait une meilleure option ?

**Comment by Rudloff** [comment]
Une solution serait de remplacer le captcha par une question pour humains (https://www.mediawiki.org/wiki/Extension:QuestyCaptcha).
Mais alors il faut bien choisir la question, pas que ça empêche des gens de s'inscrire.

**Comment by Rudloff** [comment]
Ce qu'on peut faire en plus c'est restreindre les modifications dans l'espace de nom global parce que je pense que les bots sont trop cons pour ajouter *Brouillon:* à leurs titres.

**Comment by vbonhomme** [comment]
bonne idée !

Le 14 février 2015 10:01, Pierre Rudloff <notifications@github.com> a écrit
:

> Ce qu'on peut faire en plus c'est restreindre les modifications dans
> l'espace de nom global parce que je pense que les bots sont trop cons pour
> ajouter *Brouillon:* à leurs titres.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ShakePeers/MediaKiki/issues/28#issuecomment-74367803>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by Rudloff** [comment]
C'est fait pour l'espace de nom :smile:

Pour le captcha, on pourrait mettre un truc du genre « Quelle est la couleur du logo de ShakePeers ? » (et on accepte bleu ou orange comme réponse), c'est pas trop chiant pour un humain mais un robot ne pourra pas répondre.
T'en penses quoi ?

**Comment by vbonhomme** [comment]
va bene !

Le 14 février 2015 13:17, Pierre Rudloff <notifications@github.com> a écrit
:

> C'est fait pour l'espace de nom [image: :smile:]
>
> Pour le captcha, on pourrait mettre un truc du genre « Quelle est la
> couleur du logo de ShakePeers ? » (et on accepte bleu ou orange comme
> réponse), c'est pas trop chiant pour un humain mais un robot ne pourra pas
> répondre.
> T'en penses quoi ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ShakePeers/MediaKiki/issues/28#issuecomment-74372926>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by Rudloff** [comment]
Voilà, j'ai mis ça en place. On verra si ça limite le spam.

**Comment by Rudloff** [comment]
Pas de spam depuis donc on va dire que ça fonctionne.
