### ISSUE TITLE
Change Author

### ISSUE THREAD

**Issue by vbonhomme** [ShakePeers/MediaKiki#33]
* Rajouté l'extension 'Change author' pour les cas où qqun d'autre que l'auteur aurait crée la page (eg. La bouillabaisse).
* Par ailleurs, je galère à faire substituter {{PAGECREATOR}} proprement à [ce modèle de header](https://shakepeers.org/index.php?title=MediaWiki:Hf-nsheader-Revision) alors que {{PAGECONTRIBUTORS}} fonctionne bien...

**Comment by Rudloff** [comment]
Ça fonctionnait ChangeAuthor finalement ?

**Comment by vbonhomme** [comment]
je crois bien !


2015-02-22 22:41 GMT+01:00 Pierre Rudloff <notifications@github.com>:

> Ça fonctionnait ChangeAuthor finalement ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ShakePeers/MediaKiki/issues/33#issuecomment-75462706>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>
