### ISSUE TITLE
Common.css

### ISSUE THREAD

**Issue by vbonhomme** [ShakePeers/MediaKiki#37]
nous sort une erreur.

J'allais y rajouter ça, pour faire des miniatures un poil plus jolies, démarquées : 

```
.thumb.tright {
    background: none repeat scroll 0 0 #f2f2f2;
    font-size: 80%;
    margin-bottom: 10px;
    margin-left: 40px;
    padding: 10px;
}
```

**Comment by Rudloff** [comment]
C'est la dernière version du plugin TwitterCards qui cause le bug. J'ai rétabli une version précédente et ça a l'air bon.

**Comment by vbonhomme** [comment]
Tu es le Zorro de la hotline :+1:

**Comment by vbonhomme** [comment]
des [nouveaux soucis](https://shakepeers.org/Sp%C3%A9cial:Recherche)  du coup

**Comment by Rudloff** [comment]
Bon, je désactive le plugin, il cause trop de souci.
Et du coup, je rouvre https://github.com/ShakePeers/MediaKiki/issues/2.
