### ISSUE TITLE
bouttons ?

### ISSUE THREAD

**Issue by vbonhomme** [ShakePeers/MediaKiki#39]
serait chouette à avoir comme modèle, par exemple pour remplacer "écrire" et "relire" dans la page contribuer et sur la homepage

inclus avec bootstrap mais [mes essais](https://shakepeers.org/Utilisateur:Vincent_Bonhomme/Test) sont non concluants.

**Comment by Rudloff** [comment]
Un truc omme ça ? https://shakepeers.org/Mod%C3%A8le:Bouton

**Comment by vbonhomme** [comment]
tu me fais rêver. et du coup on a acces à toutes les classes de bootstrap
non ?

Le 16 février 2015 14:19, Pierre Rudloff <notifications@github.com> a écrit
:

> Un truc omme ça ? https://shakepeers.org/Mod%C3%A8le:Bouton
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ShakePeers/MediaKiki/issues/39#issuecomment-74506934>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by Rudloff** [comment]
En théorié oui, mais elles auront pas toutes une bonne gueule avec notre thème (j'ai du adapter un peu le CSS du bouton là).
