### ISSUE TITLE
Breadcrumb

### ISSUE THREAD

**Issue by vbonhomme** [ShakePeers/MediaKiki#42]
catégorie minis truc, quand tu es sur une page derrière un namespace d'organisation, genre : Spécial:Liste_des_fichiers , le breadcrumb affiche (fort logiquement) 
    ShakePeers  › Spécial   ›  Liste des fichiers 
Peut être serait-ce pratique que Spécial renvoie sur Special:AllPages. La solution soft serait que "Special" sans namespace, redirige vers "Special:AllPages". Je pense que c'est la préférable, à moisn que tu veuilles coder un truc en dur. Qu'en penses tu ?

**Comment by Rudloff** [comment]
J'ai fais une redirection vers *Spécial:Pages_spéciales*, c'est ce qui me parait le plus pertinent.

**Comment by Rudloff** [comment]
Il y a sûrement un tas de redirections comme ça à ajouter.

**Comment by vbonhomme** [comment]
voué, suis dessus :o)

2015-02-17 13:03 GMT+01:00 Pierre Rudloff <notifications@github.com>:

> Il y a sûrement un tas de redirections comme ça à ajouter.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ShakePeers/MediaKiki/issues/42#issuecomment-74657692>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>
