### ISSUE TITLE
Infobox

### ISSUE THREAD

**Issue by vbonhomme** [ShakePeers/MediaKiki#43]
Je vois que l'infobow est gérée / crée par infoBox(), mais ne serait-ce pas un bon candidat pour la wikifaction également ? ou même mieux, appeller un modèle {{Infobox}} ?

* Plus j'aurai quelques commentaires (voire de quoi travailler moi-même) sur le formatage actuel
* Et des pistes d'évolution

**Comment by Rudloff** [comment]
Le problème c'est qu'on récupère des trucs dans l'infobox qui sont pas récupérables en wikicode.
On pourrait voir en créer de nouveux *magic words* avec ce dont on a besoin, mais c'est chiant.

**Comment by vbonhomme** [comment]
d'accord que c'est relou mais ce serait vraiment chouette...

Le 17 février 2015 13:53, Pierre Rudloff <notifications@github.com> a écrit
:

> Le problème c'est qu'on récupère des trucs dans l'infobox qui sont pas
> récupérables en wikicode.
> On pourrait voir en créer de nouveux *magic words* avec ce dont on a
> besoin, mais c'est chiant.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ShakePeers/MediaKiki/issues/43#issuecomment-74663198>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by vbonhomme** [comment]
par ailleurs, j'ai l'impression que la table des matières s'est faite engloutir dans InfoBox pour les NS non éditoriaux.

**Comment by Rudloff** [comment]
T'as un exemple de page ?

**Comment by vbonhomme** [comment]
https://shakepeers.org/ShakePeers

2015-02-17 14:24 GMT+01:00 Pierre Rudloff <notifications@github.com>:

> T'as un exemple de page ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ShakePeers/MediaKiki/issues/43#issuecomment-74666757>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by Rudloff** [comment]
C'est réglé pour la table des matières (https://github.com/ShakePeers/shakepeers-mediawiki-skin/commit/c8b24d85f3754ca9a760896b6dcabc5a21e25ee4).

**Comment by vbonhomme** [comment]
magnifique

2015-02-17 15:06 GMT+01:00 Pierre Rudloff <notifications@github.com>:

> C'est réglé pour la table des matières (
> ShakePeers/shakepeers-mediawiki-skin@c8b24d8
> <https://github.com/ShakePeers/shakepeers-mediawiki-skin/commit/c8b24d85f3754ca9a760896b6dcabc5a21e25ee4>
> ).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ShakePeers/MediaKiki/issues/43#issuecomment-74672166>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>
