### ISSUE TITLE
Nom de page / breadcrumb etc.

### ISSUE THREAD

**Issue by vbonhomme** [ShakePeers/MediaKiki#45]
* Vu qu'on a un super breadcrumb, pourrait n'afficher, pour les sous-pages, que le nom complet de page, plutôt que la page parente ? par ex: faire sauter "< ShakePeers:ShakePoint" là https://shakepeers.org/ShakePeers:ShakePoint/14
* Surtout, pourrait-on diminuer la taille du namespace genre "ShakePeers:" dans "ShakePeers:Contribuer" ?

**Comment by Rudloff** [comment]
Ça te va [comme ça](https://beta.shakepeers.org/Utilisateur:Test/Test) ?

**Comment by vbonhomme** [comment]
Magnifique !

**Comment by Rudloff** [comment]
C'ets en prod.

**Comment by vbonhomme** [comment]
superbe !
