### ISSUE TITLE
Quid de visual editor

### ISSUE THREAD

**Issue by vbonhomme** [ShakePeers/MediaKiki#47]
le thème n'est pas compatible n'est-ce pas ?
ce serait bieng' pourtant ;-)

**Comment by Rudloff** [comment]
Oui, il y a des soucis de compatibilité avec le thème (mais j'y travaille).

**Comment by Rudloff** [comment]
J'ai réussi à le faire fonctionner sur beta.
Le bouton est dans Outils > Modifier.

Il faudrait tester pour voir si tout fonctionne correctement.

**Comment by vbonhomme** [comment]
putain tu déchires !
demain je teste.
juste pour info, est-ce qu'on peut faire une copie de la prod vers
l'actuelle beta facilement ? vice-versa ?

Le 22 février 2015 16:13, Pierre Rudloff <notifications@github.com> a écrit
:

> J'ai réussi à le faire fonctionner sur beta.
> Le bouton est dans Outils > Modifier.
>
> Il faudrait tester pour voir si tout fonctionne correctement.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ShakePeers/MediaKiki/issues/47#issuecomment-75439736>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by Rudloff** [comment]
Tout est sur du Git donc ouais c'est pas trop compliqué à synchroniser.

**Comment by CarolAnnO** [comment]
Alors, pour simplifier le truc vu que la plupart des auteurs ne seront pas forcément familiers avec wiki, il faudrait mettre en avant l'éditeur visuel. Genre quand on clique sur le crayon on passe par l'éditeur visuel. Garder "l'option wiki" dans Outils (pour nous et les éditeurs). En plus via l'éditeur visuel il y a une possibilité d'ajouter des commentaires (via "insérer").. si ça marchait le truc des commentaires (pour le moment ça marche pas) on a réglé un truc chouette :) J'espère.

**Comment by vbonhomme** [comment]
<3

**Comment by vbonhomme** [comment]
putain ça c'est le futur de l'humanité : http://fr.wikipedia.org/wiki/Projet:Mod%C3%A8le/TemplateData

**Comment by Rudloff** [comment]
@CarolAnnO, l'éditeur visuel est activé sur beta.shakepeers.org, mais j'aimerais vraiment qu'on vérifie qu'il fonctionne correctement avant de le mettre par défaut.
Un des problèmes aussi est qu'il utilise vachement plus de ressources que l'éditeur normal et donc met longtemps à charger.

**Comment by CarolAnnO** [comment]
ok merci. J'ai un poil testé sur la beta ce matin, c'est là que j'ai découvert l'option commentaires dans "insérer" (qui ne marche pas quand on publie un com'), ça faisait un moment que j'avais pas joué avec l'éditeur visuel. Je comprends l'aspect lourd du truc mais si les com' marchent ce serait top de le mettre "par défaut". Comment je peux t'aider pour mieux tester ?

**Comment by vbonhomme** [comment]
au delà de l'édition, ça lubrifie pas mal de choses : http://fr.wikipedia.org/wiki/Aide:%C3%89diteurVisuel

**Comment by Rudloff** [comment]
J'ai modifié la configuration de l'éditeur visuel et les commentaires ont l'air de fonctionner. (Il faut vider votre cache d'abord pour être sûr d'avoir la dernière version.)
Par contre, ils ne s'affichent que dans l'éditeur, hein.

Ce qu'il faudrait faire, c'est tester une à une toutes les fonctionnalités de l'éditeur visuel et noter celles qui ne fonctionnent pas.

**Comment by vbonhomme** [comment]
les commentaires c'est cool !

peut on ouvrir le ve au delà de la chaine éditoriale ?

**Comment by vbonhomme** [comment]
sur beta I mean

**Comment by Rudloff** [comment]
Comment ça ?

**Comment by CarolAnnO** [comment]
Yo, je teste l'éditeur visuel sur beta. Ce qui était cool c'était les commentaires, tout va bien, on peut le faire via l'EV ou via le wikitexte mais par contre ils n'apparaissent pas une fois l'article publié :/

**Comment by Rudloff** [comment]
Oui, il s'agit de commentaires uniquement pour l'édition.

**Comment by vbonhomme** [comment]
ouais parce qu'ils sont dans un  ce qui précisément
empêche d'être interprété.
mais bon, vu que l'éditeur le parse, pourquoi pas...

besotazos !

v

Le 26 mars 2015 17:43, CarolAnnO <notifications@github.com> a écrit :

> Yo, je teste l'éditeur visuel sur beta. Ce qui était cool c'était les
> commentaires, tout va bien, on peut le faire via l'EV ou via le wikitexte
> mais par contre ils n'apparaissent pas une fois l'article publié :/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ShakePeers/MediaKiki/issues/47#issuecomment-86613755>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by CarolAnnO** [comment]
OK ok :) du coup garder en tête que lors de la version de travail, on a accès aux commentaires via l'édition pour le tuto des auteurs/relecteurs. Merci <3 Ou alors voir si techniquement on peut afficher les commentaires une fois publiés uniquement sur la version de travail... ça pinaille :)

**Comment by Rudloff** [comment]
On peut se débrouiller avec JavaScript pour afficher les commentaires sur la page en lecture, mais ça serait du bricolage.

**Comment by CarolAnnO** [comment]
Non mais après faut faire aussi avec le wiki.. donc que ça reste comme ça ne me pose pas de problème en fait.. s'il y a des commentaires globaux, ça passe en page discussion sinon ben version de travail en mode édition. Faut juste garder en tête l'outil de commentaire pour le tuto détaillé des auteurs/relecteurs.

**Comment by Rudloff** [comment]
C'est activé en production.
