### ISSUE TITLE
PageCreator

### ISSUE THREAD

**Issue by vbonhomme** [ShakePeers/MediaKiki#49]
erreur!
cf https://shakepeers.org/Revision:Favoriser_la_biodiversit%C3%A9_urbaine/Compost

**Comment by Rudloff** [comment]
J'ai désactivé les avertissements.
Mais bon PageCreator n'est plus mis à jour depuis 2012...

**Comment by vbonhomme** [comment]
problème: c'est le viewer qui est affiché :~(
https://shakepeers.org/Revision:Favoriser_la_biodiversit%C3%A9_urbaine/Compost


2015-03-14 16:05 GMT+01:00 Pierre Rudloff <notifications@github.com>:

> Closed #49 <https://github.com/ShakePeers/MediaKiki/issues/49>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ShakePeers/MediaKiki/issues/49#event-253751677>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by Rudloff** [comment]
Bon, j'ai corrigé le bug de PageCreator et j'ai mis ça là : https://github.com/ShakePeers/mediawiki-PageCreator
