### ISSUE TITLE
/Review

### ISSUE THREAD

**Issue by vbonhomme** [ShakePeers/MediaKiki#52]
Le comportement de PageCreator semble indiquer que Review est supprimée au merge, et recrée à la review ?

https://shakepeers.org/Revision:La_bouillabaisse_du_futur/Review

Pourrait on rendre l'auteur de l'article, créateur aussi de la page /Review associée ? Bref, la créer au départ et une fois pour toutes ?

**Comment by vbonhomme** [comment]
On pourrait compter aussi le nombre d'éditions de la branche /Review en avant de la branche principale (en bits/mots/edits que que tu veux)

**Comment by Rudloff** [comment]
Pas vraiment de moyen simple de faire une modification au nom d'un autre compte avec MediaWiki donc j'ai pas de solution qui demanderait pas trop de développement pour le coup de l'auteur.

Ce qui serait pas trop chiant à ajouter sur la page de diff, c'est le nombre de lignes modifiées, les mots ça demande un peu plus de boulot mais faisable, les edits pas possible avec le système actuel.
