### ISSUE TITLE
Review / Main

### ISSUE THREAD

**Issue by vbonhomme** [ShakePeers/MediaKiki#53]
* Il faudrait un système plus intuitif de passage à la dernière version de l'auteur à celle en review : un interrupteur ?
* Surtout, il faudrait tomber sur /Review systématiquement à l'arrivée sur l'article

**Comment by Rudloff** [comment]
Pour tomber directement sur */Review*, on pourrait ajouter une option *addsubpage* à [DPL](https://github.com/ShakePeers/mediawiki-extensions-intersection) qui rajouterait un */quelquechose* au bout de chaque lien.

**Comment by atulebamboo** [comment]
Merci mais selon vincent c'est pas le plus élégant....

**Comment by atulebamboo** [comment]
Dans la même veine, pour un relecteur la seule version accessible devrait être la /Review. La version Revision: n'ayant pour seul but que le calcul du diff, elle ne devrait pas être accessible et se synchroniser avec la version /Review après validation des commentaires par l'auteur.

**Comment by Rudloff** [comment]
Mais du coup comment voir l'intention originale de l'auteur afin d'éviter d'orienter l'article trop différemment ?

**Comment by atulebamboo** [comment]
ça ne correspondrait pas à la version brouillon, celle qui contient l'intention originale. J'ai modifié le BandeauHeaderRévision en conséquences.

**Comment by Rudloff** [comment]
Ce que je peux faire, c'est que si on clique sur un article en révision dont on n'est pas l'auteur, on est redirigé vers */Review* et si on est auteur ça affiche l'article normalement.

**Comment by vbonhomme** [comment]
une possibilité de diff actuel/entrée en révision (ou sortie de brouillon) ?

2015-03-14 20:06 GMT+01:00 Pierre Rudloff <notifications@github.com>:

> Mais du coup comment voir l'intention originale de l'auteur afin d'éviter
> d'orienter l'article trop différemment ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ShakePeers/MediaKiki/issues/53#issuecomment-80676523>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by Rudloff** [comment]
Bah le diff actuel fait déjà ça. Ou j'ai pas compris ?

**Comment by vbonhomme** [comment]
non je voulais dire, même après plusieurs allers retours de review,
toujours avoir un *raccourci* vers le diff entre la toute première version
et l'actuelle (pour l'orientation g"nérale comme tu disais)

2015-03-14 21:25 GMT+01:00 Pierre Rudloff <notifications@github.com>:

> Bah le diff actuel fait déjà ça. Ou j'ai pas compris ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ShakePeers/MediaKiki/issues/53#issuecomment-80703116>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by Rudloff** [comment]
Oui, ça peut se faire ça (un jour, quand j'aurais le temps :/).

**Comment by atulebamboo** [comment]
On arrive à un consensus sur les pages dont nous avons besoin. Il nous faudrait les pages suivantes:
 - la "version originale" de l'auteur, son intention de départ. Vu que l'on supprime la version Brouillon: lors du passage en Révision: il faudrait garder la première version de Révision: .

 - la "dernière version validée par l'auteur" qui n'a pas, à mon sens, à être accessible car elle complique la compréhension du processus éditorial. Elle ne sert qu'à calculer le diff. De plus, le lien vers le diff renvoie à l'erreur suivante:  Fatal error: Call to a member function getId() on a non-object in /home/shakepeers/mediawiki/extensions/ReviewAndMerge/SpecialReviewAndMerge.php on line 250
 - la "version de travail" , la /Review qui est celle sur laquelle on devrait tomber par défaut, que l'on soit auteur ou relecteur.
- l'ensemble des modifications apportées, i.e. le diff entre la version originale et la /Review.
- les dernières modifications apportées, le diff entre la dernière validée par l'auteur et la /Review.

J'ai modifié le bandeau en conséquences mais il reste à:
- implémenter la récupération de la version originale
- calculer le diff entre /Review et l'original

**Comment by Rudloff** [comment]
Pour l'erreur PHP, c'est quand la page /Review n'existe pas encore, ça devrait être réglé (https://github.com/ShakePeers/mediawiki-ReviewAndMerge/issues/4).

Du coup, si vous voulez la Review par défaut, il faudrait presque inverser tout le système, avoir la Review sur l'article normal et la version validée par l'auteur sur /quelquechose. Par contre ça va poser problème avec les articles existants et ça ne résout pas le fait de garder l'original.
