### ISSUE TITLE
Importer des pdf

### ISSUE THREAD

**Issue by CarolAnnO** [ShakePeers/MediaKiki#54]
Pour le moment le format .pdf n'est pas accepté pour l'importation de fichiers. Peut-on ajouter ce format ? Merci :) bisou

**Comment by Rudloff** [comment]
Voilà, j'ai autorisé les PDF et j'ai activé cette extension : https://www.mediawiki.org/wiki/Extension:PdfHandler

**Comment by CarolAnnO** [comment]
merci <3
