### ISSUE TITLE
Boutons icones skin

### ISSUE THREAD

**Issue by vbonhomme** [ShakePeers/MediaKiki#55]
Pourrait on avoir les icones, voire les boutons, sous forme de modèle ?
Par exemple {{BoutonOutils}} reproduirait, avec une image et un lien, le bouton  "Outils" du skin
La compatibilité avec vector et autres est peut-être un problème (pour les intégristes).

**Comment by atulebamboo** [comment]
A l'heure actuelle il faut apposer la balise  {{Révision?}} pour demander la révision. Pourrait on avoir un bouton qui fasse ça automatiquement ?

**Comment by vbonhomme** [comment]
tu veux dire au jour d'aujourd'hui ?
hihahi

Le 27 mars 2015 12:15, atulebamboo <notifications@github.com> a écrit :

> A l'heure actuelle il faut apposer la balise {{Révision?}} pour demander
> la révision. Pourrait on avoir un bouton qui fasse ça automatiquement ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ShakePeers/MediaKiki/issues/55#issuecomment-86904385>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>
