### ISSUE TITLE
quotes ouvrantes et pas fermantes

### ISSUE THREAD

**Issue by vbonhomme** [ShakePeers/MediaKiki#56]
là : https://shakepeers.org/Cat%C3%A9gorie:Biologie

aussi, un embryon de tentative de portaillisation.

**Comment by Rudloff** [comment]
C'est apparemment la police qui ne connait pas le caractère *»*...

**Comment by Rudloff** [comment]
Je ne l'explique pas mais en enlevant le gras sur le titre, c'est bon.
