### ISSUE TITLE
spam

### ISSUE THREAD

**Issue by vbonhomme** [ShakePeers/MediaKiki#63]
tjs pas mal d'utilisateurs qui s'incrustent : https://shakepeers.org/Sp%C3%A9cial:Liste_des_utilisateurs

**Comment by Rudloff** [comment]
Bah non, pas depuis qu'on a augmenté les mesures antispam en février : https://shakepeers.org/index.php?title=Sp%C3%A9cial%3AListe_des_utilisateurs&username=&group=&creationSort=1&desc=1&limit=50

**Comment by vbonhomme** [comment]
dacc, alors je supprimerai juste les emmerdeurs

2015-12-18 11:54 GMT+01:00 Pierre Rudloff <notifications@github.com>:

> Closed #63 <https://github.com/ShakePeers/MediaKiki/issues/63>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ShakePeers/MediaKiki/issues/63#event-495710970>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>
