### ISSUE TITLE
nb of active users

### ISSUE THREAD

**Issue by vbonhomme** [ShakePeers/MediaKiki#64]
souci de comptage, cf https://shakepeers.org/ShakePeers:Footer

**Comment by Rudloff** [comment]
Les utilisateurs actifs sont ceux « qui ont exercé une quelconque activité au cours des 30 derniers jours ».

**Comment by vbonhomme** [comment]
ah, ya ptet un petit lag, on est passé de 1 à 8, c'est cool.

Le 18 décembre 2015 à 11:55, Pierre Rudloff <notifications@github.com> a
écrit :

> Les utilisateurs actifs sont ceux « qui ont exercé une quelconque activité
> au cours des 30 derniers jours ».
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ShakePeers/MediaKiki/issues/64#issuecomment-165747606>
> .
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>
